apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-eks-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ilgazcolak/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: aws-eks-demo-ns

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
